# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Vanilla JS Frontend to Azure Web App - eramus-cc2025-ui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # O Frontend NÃO PRECISA de um job 'build' complexo, apenas de empacotamento.
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Isso é necessário para solicitar o JWT (OIDC)
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Empacotar apenas os ficheiros estáticos (HTML/JS/CSS)
      - name: Create Static Package (ZIP)
        run:
          WORKSPACE="${{ github.workspace }}"
          STATIC_DIR="$WORKSPACE/src/main/resources/static"
          cd $STATIC_DIR && zip -r frontend_package.zip . && mv frontend_package.zip $WORKSPACE/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D9E190CAF8414EEF932D3FA7AFC32B5D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B0FEF874DC994CA692B23C0010D39F50 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2356144817D849258D463FE517E8FD74 }}

      - name: Deploy Frontend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eramus-cc2025-ui'
          slot-name: 'Production'
          package: '${{ github.workspace }}/frontend_package.zip'